
spring.application.name=discografia2

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://eva2_spring:GIhMo3ua0acgTztw@cluster-spring.znbiq9h.mongodb.net/discografica-db?appName=cluster-spring}

spring.data.mongodb.database=discografica-db

server.port=${PORT:8080}
